config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  post 'login' => 'sessions#create'
  get 'profile' => 'pages#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :must_login

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

    def logged_in?
      !!current_user
    end

    def must_login
      if !logged_in?
        flash[:danger] = "Please log-in"
        redirect_to login_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :must_login, only: [:show]
  def index
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome to MYAuth"
      redirect_to root_path
    else
      flash.now[:danger] = "Can't Login"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:info] = "You're Offline"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myauth</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Myauth', '#', class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Hpme', '#' %></li>
            <% if !logged_in? %>
              <li><%= link_to 'Login', login_path %></li>
            <% else %>
              <li><%= link_to 'Profile', profile_path %></li>
              <li><%= link_to 'Logout', logout_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1> Welcome! </h1>
  <p> Joz Auth </p>
</div>

app/views/pages/show.html.erb
<div class="row">
  <div class="col-md-6 md-offset-3">
    <h1>Profile</h1>
    <% user = current_user %>
    <table class="table">
      <tr>
        <th>Name</th>
        <td><%= user.name %></td>
      </tr>
      <tr>
        <th>Email</th>
        <td><%= user.email %></td>
      </tr>
    </table>
  </div>
</div>